#!/usr/bin/env node
/**
 * Scans assets/gallery/ and writes js/gallery-manifest.js with the GALLERY array.
 * Run manually: node scripts/build-gallery.js
 * Runs automatically on every Vercel deploy via vercel.json buildCommand.
 *
 * Filename → alt text: hyphens/underscores become spaces, words are capitalised.
 * Example: "mongolian-beef.webp" → "Mongolian Beef"
 */

const fs   = require('fs');
const path = require('path');

const ROOT        = path.join(__dirname, '..');
const GALLERY_DIR = path.join(ROOT, 'assets', 'gallery');
const OUT_FILE    = path.join(ROOT, 'js', 'gallery-manifest.js');

const SUPPORTED = new Set(['.webp', '.jpg', '.jpeg', '.png', '.gif', '.avif']);

function toAlt(filename) {
  return filename
    .replace(/\.[^.]+$/, '')          // strip extension
    .replace(/[-_]+/g, ' ')           // dashes/underscores → spaces
    .replace(/\b\w/g, c => c.toUpperCase()); // Title Case
}

const files = fs.readdirSync(GALLERY_DIR)
  .filter(f => SUPPORTED.has(path.extname(f).toLowerCase()))
  .sort();

if (!files.length) {
  console.warn('build-gallery: no images found in assets/gallery/ — writing empty array.');
}

const gallery = files.map(f => ({ img: `assets/gallery/${f}`, alt: toAlt(f) }));

const output = [
  '/* ---------------------------------------------------------------',
  '   Auto-generated by scripts/build-gallery.js — do not edit here.',
  '   Add / remove images in assets/gallery/ then re-run the script.',
  '   --------------------------------------------------------------- */',
  `const GALLERY = ${JSON.stringify(gallery, null, 2)};`,
  '',
].join('\n');

fs.writeFileSync(OUT_FILE, output, 'utf8');
console.log(`build-gallery: wrote ${gallery.length} image(s) to js/gallery-manifest.js`);
